"""
app.py
=======
Flask web app that presents the Week 4 pipeline results AND lets a user
upload a leaf image to get a live disease prediction from the trained model.

Sections:
    - Evaluation metrics loaded from outputs/results/metrics.json
    - All figures generated by main.py, from outputs/figures/
    - A link to view/download outputs/results/classification_report.txt
    - An upload form ("Scan Image") that preprocesses an uploaded image
      through the exact same pipeline used during training
      (src/preprocessing.py + src/feature_extraction.py), runs it through
      the model saved by main.py (outputs/results/baseline_model.joblib +
      baseline_scaler.joblib, or outputs/results/cnn_model.keras if
      TensorFlow was available when main.py ran), and displays the
      predicted class + confidence score.

Run (from the project root, AFTER running src/main.py at least once so
that outputs/ and the trained model are populated):

    python src/app.py

Then open http://127.0.0.1:5000/ in a browser.
"""

from __future__ import annotations

import io
import json
import os
import sys
import uuid

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
from flask import (
    Flask, render_template_string, send_from_directory, abort, request, url_for
)
from werkzeug.utils import secure_filename

from src.preprocessing import preprocess_image
from src.feature_extraction import extract_features

# ---------------------------------------------------------------------------
# Paths - anchored to the project root regardless of the current working
# directory the app is launched from.
# ---------------------------------------------------------------------------
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUTS_DIR = os.path.join(PROJECT_ROOT, "outputs")
FIGURES_DIR = os.path.join(OUTPUTS_DIR, "figures")
RESULTS_DIR = os.path.join(OUTPUTS_DIR, "results")
METRICS_PATH = os.path.join(RESULTS_DIR, "metrics.json")
REPORT_PATH = os.path.join(RESULTS_DIR, "classification_report.txt")
INFERENCE_META_PATH = os.path.join(RESULTS_DIR, "inference_meta.json")

UPLOAD_DIR = os.path.join(PROJECT_ROOT, "outputs", "uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)

ALLOWED_EXTENSIONS = {"jpg", "jpeg", "png", "bmp", "tif", "tiff"}

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 10 * 1024 * 1024  # 10 MB upload cap

FIGURE_CAPTIONS = {
    "01_class_distribution.png": "Class Distribution",
    "02_image_dimensions.png": "Image Dimension Analysis",
    "03_sample_images.png": "Sample Images per Class",
    "04_before_after_preprocessing.png": "Before vs After Preprocessing",
    "05_augmentation_examples.png": "Data Augmentation Examples",
    "06_color_analysis.png": "Per-Class Color Channel Distributions",
    "07_feature_distributions.png": "Engineered Feature Distributions",
    "08_texture_edge_examples.png": "Texture & Edge Feature Examples",
    "09_confusion_matrix.png": "Confusion Matrix",
}


# ---------------------------------------------------------------------------
# Model loading (lazy + cached) for the "Scan Image" prediction feature
# ---------------------------------------------------------------------------
_MODEL_CACHE = {"loaded": False}


def _load_inference_bundle():
    """Load (and cache) whatever model main.py trained, plus its metadata.
    Returns a dict, or None if outputs/results/inference_meta.json doesn't
    exist yet (i.e. main.py hasn't been run)."""
    if _MODEL_CACHE["loaded"]:
        return _MODEL_CACHE.get("bundle")

    _MODEL_CACHE["loaded"] = True
    if not os.path.exists(INFERENCE_META_PATH):
        _MODEL_CACHE["bundle"] = None
        return None

    with open(INFERENCE_META_PATH, "r") as f:
        meta = json.load(f)

    bundle = {"meta": meta}
    try:
        if meta["model_type"] == "baseline":
            import joblib
            bundle["clf"] = joblib.load(os.path.join(RESULTS_DIR, meta["baseline_model_path"]))
            bundle["scaler"] = joblib.load(os.path.join(RESULTS_DIR, meta["baseline_scaler_path"]))
        elif meta["model_type"] == "cnn":
            import tensorflow as tf
            bundle["cnn_model"] = tf.keras.models.load_model(
                os.path.join(RESULTS_DIR, meta["cnn_model_path"])
            )
        else:
            bundle = None
    except Exception as e:
        print(f"[app] Failed to load trained model for inference: {e}")
        bundle = None

    _MODEL_CACHE["bundle"] = bundle
    return bundle


def allowed_file(filename: str) -> bool:
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


def run_prediction(image_path: str):
    """Run the uploaded image through the exact preprocessing pipeline used
    during training, then through whichever model main.py trained.
    Returns (predicted_class, confidence_pct, top3 list[(class, pct)]) or
    raises an Exception with a user-friendly message on failure."""
    bundle = _load_inference_bundle()
    if bundle is None:
        raise RuntimeError(
            "No trained model found. Run 'python src/main.py' first to train "
            "and save a model, then try scanning again."
        )

    meta = bundle["meta"]
    img_size = tuple(meta["img_size"])
    class_names = meta["class_names"]

    # Same preprocessing used for every training/val/test image.
    img = preprocess_image(image_path, size=img_size, apply_denoise=meta.get("apply_denoise", True))

    if meta["model_type"] == "baseline":
        feats = extract_features(img)
        feature_cols = meta["feature_columns"]
        x = np.array([[feats.get(c, 0.0) for c in feature_cols]], dtype=np.float32)
        x_scaled = bundle["scaler"].transform(x)
        clf = bundle["clf"]
        probs = clf.predict_proba(x_scaled)[0]
        classes = list(clf.classes_)
    else:  # cnn
        x = np.expand_dims(img.astype(np.float32), axis=0)
        probs = bundle["cnn_model"].predict(x, verbose=0)[0]
        classes = class_names

    order = np.argsort(probs)[::-1]
    top3 = [(str(classes[i]), float(probs[i]) * 100.0) for i in order[:3]]
    predicted_class, confidence = top3[0]
    return predicted_class, confidence, top3


PAGE_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Plant Disease Detection - Week 4 Results</title>
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
         margin: 0; background: #f4f6f5; color: #1f2a24; }
  header { background: #1f4d3a; color: #fff; padding: 24px 32px; }
  header h1 { margin: 0 0 4px 0; font-size: 1.6rem; }
  header p { margin: 0; opacity: 0.85; }
  main { max-width: 1100px; margin: 0 auto; padding: 24px 32px 64px; }
  section { margin-bottom: 40px; }
  h2 { border-bottom: 2px solid #d8e3dc; padding-bottom: 8px; color: #1f4d3a; }
  .metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
                  gap: 16px; margin-top: 16px; }
  .metric-card { background: #fff; border-radius: 10px; padding: 16px 18px;
                 box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  .metric-card .value { font-size: 1.6rem; font-weight: 700; color: #1f4d3a; }
  .metric-card .label { font-size: 0.85rem; color: #5b6b62; text-transform: uppercase;
                         letter-spacing: 0.04em; margin-top: 4px; }
  .figure-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
                 gap: 24px; margin-top: 16px; }
  .figure-card { background: #fff; border-radius: 10px; overflow: hidden;
                 box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  .figure-card img { width: 100%; display: block; }
  .figure-card .caption { padding: 10px 14px; font-size: 0.92rem; color: #37423b; }
  .warning { background: #fff4e5; border: 1px solid #f0c987; color: #7a5210;
             padding: 14px 18px; border-radius: 8px; }
  .error { background: #fdeaea; border: 1px solid #ec9a9a; color: #8a2626;
           padding: 14px 18px; border-radius: 8px; margin-top: 16px; }
  a.button, button.button { display: inline-block; margin-top: 8px; background: #1f4d3a;
             color: #fff; padding: 10px 18px; border-radius: 6px; text-decoration: none;
             font-weight: 600; border: none; cursor: pointer; font-size: 0.95rem; }
  a.button:hover, button.button:hover { background: #163a2b; }
  pre { background: #10241a; color: #d7ecdf; padding: 16px; border-radius: 8px;
        overflow-x: auto; font-size: 0.85rem; }
  footer { text-align: center; color: #7b8a80; font-size: 0.85rem; padding: 24px; }

  /* --- Scanner / upload card --- */
  .scanner-card { background: #fff; border-radius: 12px; padding: 24px;
                   box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  .scanner-form { display: flex; flex-wrap: wrap; gap: 14px; align-items: center; }
  .file-input-wrap { position: relative; }
  .file-input-wrap input[type=file] { font-size: 0.9rem; }
  .scanner-hint { font-size: 0.85rem; color: #5b6b62; margin-top: 6px; }
  .predict-result { margin-top: 22px; display: flex; gap: 24px; flex-wrap: wrap;
                     align-items: flex-start; }
  .predict-result img { max-width: 260px; border-radius: 10px;
                         box-shadow: 0 1px 4px rgba(0,0,0,0.15); }
  .predict-box { flex: 1; min-width: 240px; }
  .predict-class { font-size: 1.4rem; font-weight: 700; color: #1f4d3a; }
  .confidence-bar-track { background: #e4ece7; border-radius: 6px; height: 10px;
                           width: 100%; margin-top: 6px; overflow: hidden; }
  .confidence-bar-fill { background: #2f7d54; height: 100%; }
  .top3-row { display: flex; justify-content: space-between; font-size: 0.9rem;
              padding: 6px 0; border-bottom: 1px solid #eef2ef; }
  .badge { display: inline-block; background: #e4ece7; color: #1f4d3a;
           border-radius: 999px; padding: 3px 10px; font-size: 0.78rem;
           font-weight: 600; margin-left: 8px; }
</style>
</head>
<body>
<header>
  <h1>Plant Disease Detection &mdash; Week 4</h1>
  <p>Data Preprocessing &amp; Feature Engineering Strategies &mdash; results dashboard</p>
</header>
<main>
  {% if not metrics and not figures %}
  <div class="warning">
    No results found yet. Run <code>python src/main.py</code> from the project root
    first to generate <code>outputs/</code>, then refresh this page.
  </div>
  {% endif %}

  <section>
    <h2>Scan a Leaf Image
      {% if model_type %}<span class="badge">model: {{ model_type }}</span>{% endif %}
    </h2>
    <div class="scanner-card">
      {% if not model_available %}
      <div class="warning">
        No trained model available yet for prediction. Run
        <code>python src/main.py</code> first, then refresh this page.
      </div>
      {% else %}
      <form class="scanner-form" action="{{ url_for('scan') }}" method="post" enctype="multipart/form-data">
        <div class="file-input-wrap">
          <input type="file" name="image" accept=".jpg,.jpeg,.png,.bmp,.tif,.tiff" required>
        </div>
        <button class="button" type="submit">&#128269; Scan Image</button>
      </form>
      <div class="scanner-hint">
        Upload a photo of a plant leaf (JPG/PNG/BMP/TIFF, max 10&nbsp;MB). The app
        preprocesses it the same way as training data and predicts one of:
        {{ class_names|join(', ') if class_names else '' }}.
      </div>
      {% endif %}

      {% if scan_error %}
      <div class="error">{{ scan_error }}</div>
      {% endif %}

      {% if prediction %}
      <div class="predict-result">
        <img src="{{ uploaded_image_url }}" alt="Uploaded leaf image">
        <div class="predict-box">
          <div class="predict-class">{{ prediction.predicted_class }}</div>
          <div>Confidence: <strong>{{ "%.1f"|format(prediction.confidence) }}%</strong></div>
          <div class="confidence-bar-track">
            <div class="confidence-bar-fill" style="width: {{ prediction.confidence }}%;"></div>
          </div>
          <div style="margin-top:16px; font-weight:600; color:#37423b;">Top predictions</div>
          {% for cls, pct in prediction.top3 %}
          <div class="top3-row"><span>{{ cls }}</span><span>{{ "%.1f"|format(pct) }}%</span></div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
    </div>
  </section>

  {% if metrics %}
  <section>
    <h2>Evaluation Metrics</h2>
    <div class="metrics-grid">
      {% for key, value in metrics.items() %}
      <div class="metric-card">
        <div class="value">{{ "%.3f"|format(value) if value is number else value }}</div>
        <div class="label">{{ key.replace('_', ' ') }}</div>
      </div>
      {% endfor %}
    </div>
    {% if report_exists %}
    <a class="button" href="{{ url_for('download_report') }}">View full classification_report.txt</a>
    {% endif %}
  </section>
  {% endif %}

  {% if report_exists %}
  <section>
    <h2>Classification Report</h2>
    <pre>{{ report_text }}</pre>
  </section>
  {% endif %}

  {% if figures %}
  <section>
    <h2>Figures</h2>
    <div class="figure-grid">
      {% for fname, caption in figures %}
      <div class="figure-card">
        <img src="{{ url_for('serve_figure', filename=fname) }}" alt="{{ caption }}">
        <div class="caption">{{ caption }}</div>
      </div>
      {% endfor %}
    </div>
  </section>
  {% endif %}
</main>
<footer>Plant Disease Detection &mdash; Week 4 pipeline results, served locally with Flask.</footer>
</body>
</html>
"""


def load_metrics():
    if not os.path.exists(METRICS_PATH):
        return None
    with open(METRICS_PATH, "r") as f:
        return json.load(f)


def list_figures():
    if not os.path.isdir(FIGURES_DIR):
        return []
    files = sorted(f for f in os.listdir(FIGURES_DIR) if f.lower().endswith((".png", ".jpg", ".jpeg")))
    return [(f, FIGURE_CAPTIONS.get(f, f)) for f in files]


def _render_index(**extra):
    metrics = load_metrics()
    figures = list_figures()
    report_exists = os.path.exists(REPORT_PATH)
    report_text = ""
    if report_exists:
        with open(REPORT_PATH, "r") as f:
            report_text = f.read()

    bundle = _load_inference_bundle()
    model_available = bundle is not None
    model_type = bundle["meta"]["model_type"] if bundle else None
    class_names = bundle["meta"]["class_names"] if bundle else []

    ctx = dict(
        metrics=metrics,
        figures=figures,
        report_exists=report_exists,
        report_text=report_text,
        model_available=model_available,
        model_type=model_type,
        class_names=class_names,
        scan_error=None,
        prediction=None,
        uploaded_image_url=None,
    )
    ctx.update(extra)
    return render_template_string(PAGE_TEMPLATE, **ctx)


@app.route("/")
def index():
    return _render_index()


@app.route("/scan", methods=["POST"])
def scan():
    file = request.files.get("image")
    if file is None or file.filename == "":
        return _render_index(scan_error="Please choose an image file to scan.")

    if not allowed_file(file.filename):
        return _render_index(
            scan_error="Unsupported file type. Please upload a JPG, PNG, BMP, or TIFF image."
        )

    safe_name = secure_filename(file.filename)
    unique_name = f"{uuid.uuid4().hex}_{safe_name}"
    saved_path = os.path.join(UPLOAD_DIR, unique_name)
    file.save(saved_path)

    try:
        predicted_class, confidence, top3 = run_prediction(saved_path)
        prediction = {
            "predicted_class": predicted_class,
            "confidence": confidence,
            "top3": top3,
        }
        return _render_index(
            prediction=prediction,
            uploaded_image_url=url_for("serve_upload", filename=unique_name),
        )
    except Exception as e:
        return _render_index(scan_error=f"Could not analyze this image: {e}")


@app.route("/uploads/<path:filename>")
def serve_upload(filename):
    return send_from_directory(UPLOAD_DIR, filename)


@app.route("/figures/<path:filename>")
def serve_figure(filename):
    if not os.path.isdir(FIGURES_DIR):
        abort(404)
    return send_from_directory(FIGURES_DIR, filename)


@app.route("/results/classification_report.txt")
def download_report():
    if not os.path.exists(REPORT_PATH):
        abort(404)
    return send_from_directory(RESULTS_DIR, "classification_report.txt", mimetype="text/plain")


if __name__ == "__main__":
    print(f"[app] Project root: {PROJECT_ROOT}")
    print(f"[app] Reading metrics from: {METRICS_PATH}")
    print(f"[app] Reading figures from: {FIGURES_DIR}")
    print(f"[app] Inference metadata: {INFERENCE_META_PATH} "
          f"({'found' if os.path.exists(INFERENCE_META_PATH) else 'NOT found - run src/main.py first'})")
    print("[app] Starting Flask site at http://127.0.0.1:5000/")
    app.run(debug=True, host="127.0.0.1", port=5000)
